/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BusinessContractInterface extends Interface {
  getFunction(
    nameOrSignature: "counters" | "executeFromPQC" | "trustedGatewayRelayer"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PQCActionExecuted"): EventFragment;

  encodeFunctionData(
    functionFragment: "counters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeFromPQC",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedGatewayRelayer",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "counters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeFromPQC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedGatewayRelayer",
    data: BytesLike
  ): Result;
}

export namespace PQCActionExecutedEvent {
  export type InputTuple = [
    pqcSender: AddressLike,
    relayer: AddressLike,
    value: BigNumberish,
    newCounter: BigNumberish
  ];
  export type OutputTuple = [
    pqcSender: string,
    relayer: string,
    value: bigint,
    newCounter: bigint
  ];
  export interface OutputObject {
    pqcSender: string;
    relayer: string;
    value: bigint;
    newCounter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BusinessContract extends BaseContract {
  connect(runner?: ContractRunner | null): BusinessContract;
  waitForDeployment(): Promise<this>;

  interface: BusinessContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  counters: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  executeFromPQC: TypedContractMethod<
    [pqcSender: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  trustedGatewayRelayer: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "counters"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeFromPQC"
  ): TypedContractMethod<
    [pqcSender: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustedGatewayRelayer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PQCActionExecuted"
  ): TypedContractEvent<
    PQCActionExecutedEvent.InputTuple,
    PQCActionExecutedEvent.OutputTuple,
    PQCActionExecutedEvent.OutputObject
  >;

  filters: {
    "PQCActionExecuted(address,address,uint256,uint256)": TypedContractEvent<
      PQCActionExecutedEvent.InputTuple,
      PQCActionExecutedEvent.OutputTuple,
      PQCActionExecutedEvent.OutputObject
    >;
    PQCActionExecuted: TypedContractEvent<
      PQCActionExecutedEvent.InputTuple,
      PQCActionExecutedEvent.OutputTuple,
      PQCActionExecutedEvent.OutputObject
    >;
  };
}
